### ISSUE TITLE
UI scaling is off on high DPI/retina displays with window.devicePixelRatio != 1

### ISSUE THREAD

**Issue by juj** [karimnaaji/melt-emscripten#1]
First off, super cool to see you have an Emscripten demo of the algorithm! Amazing work <3

Something I notice that happens with the demo applet is if one has a high DPI display with `window.devicePixelRatio` > 1. In such case, the UI scaling seems to be off with respect to the size of the canvas.

One way to simulate this on non-retina displays is to use ctrl+mouse wheel to zoom the page in or out. That will change `window.devicePixelRatio`. Zoom in to e.g. 200% and then reload the page, and notice how the UI is twice as large, and the interaction with the mouse is off by a factor of 2x.

(In my case, since MacBooks have a DPI scale of 2x at 100% zoom level, currently I needed to zoom out the page to 50% to get the DPI scale back to 1x for the UI scaling to match up)

**Comment by karimnaaji** [comment]
Hey @juj , thanks for notifying me and the kind words! I'll look at updating this as I see it broken too on a retina display.

**Comment by karimnaaji** [comment]
Re-uploaded a version, it's now fixed, thanks for notifying!
